### ISSUE TITLE
PHP 8.2 and on?

### ISSUE THREAD

**Issue by vespino** [Samoual/class.templatepower.inc.php#2]
I haven’t yet looked into your work, but I’m currently experiencing problems upgrading to PHP 8.2 and was wondering if your changes might give long term support. I have been using templatepower for years and don’t see the need to move to another system, especially since if would save a lot of time not having to.

**Comment by Samoual** [comment]
I have done this upgrade long time ago as one of my clients like you don't want to use it. And it was working with him and there was another one use it and confirm its working with him and show me one bug and I fix it if you face any issue just open issue and I will update it. Best wishes Sent from my phone-------- Original message --------From: vespino ***@***.***>Date: Sat, 13 Jan 2024, 2:39 pmTo: "Samoual/class.templatepower.inc.php" ***@***.***>Cc: Subscribed ***@***.***>Subject: [Samoual/class.templatepower.inc.php] PHP 8.2 and on? (Issue #2)
I haven’t yet looked into your work, but I’m currently experiencing problems upgrading to PHP 8.2 and was wondering if your changes might give long term support. I have been using templatepower for years and don’t see the need to move to another system, especially since if would save a lot of time not having to.

**Comment by vespino** [comment]
This is what I'm facing:

`Deprecated: Creation of dynamic property TemplatePower::$tpl_rawContent0 is deprecated in /***/public_html/templatepower/class.templatepower.inc.php on line 183`

I'm using a much older version of this class, but that throws similar errors with PHP 8.2.
